version: '3.8'

services:
  
  mongodb:
    image: mongo:latest
    container_name: finance_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db 

  
  backend:
    build: ./backend
    container_name: finance_backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      
      - MONGO_URI=mongodb://mongodb:27017/finance_manager
      - JWT_SECRET=finance_manager_secret_key_2026_!@#
    depends_on:
      - mongodb 

  
  frontend:
    build: ./frontend
    container_name: finance_frontend
    ports:
      - "80:80" 
    depends_on:
      - backend


volumes:
  mongo_data: